export const Data = [
  {
    Code: "B0012DHLK6",
    bookName: "Dhan-Sampatti Ka Manovigyan (The Psychology of Money)",
    authorName: "Morgan Housel and Asma",
    posterUrl: "https://m.media-amazon.com/images/I/71sGiVleerL._AC_UY218_.jpg",
    pricing: 150,
    releaseDate: "25 June 2021",
  },
  {
    Code: "B00K0OI42W",
    bookName: "Shrimad Bhagwat Geeta Yatharoop (Hindi)",
    authorName: "A.C. Bhaktivendanta Swami Prabhupada",
    posterUrl: "https://m.media-amazon.com/images/I/91msEbTletL._AC_UY218_.jpg",
    pricing: 235,
    releaseDate: "1 January 2019",
  },
  {
    Code: "B0055QJ4K2",
    bookName: "Think And Grow Rich - Hindi",
    authorName: "Napoleon Hill",
    posterUrl: "https://m.media-amazon.com/images/I/71UwU-b+aTS._AC_UY218_.jpg",
    pricing: 139,
    releaseDate: "1 March 2016",
  },
  {
    Code: "B003JTHWKU",
    bookName: "Rich Dad Poor Dad - 20Th Anniversary Edition - Hindi",
    authorName: "Robert Kiyosaki",
    posterUrl: "https://m.media-amazon.com/images/I/814u4vr3tzL._AC_UY218_.jpg",
    pricing: 311,
    releaseDate: "1 January 2013",
  },
  {
    Code: "B00QJDOEA4",
    bookName: "Trading in the Zone (Hindi)",
    authorName: "Mark Douglas ",
    posterUrl: "https://m.media-amazon.com/images/I/616pDr5xHYL._AC_UY218_.jpg",
    pricing: 311,
    releaseDate: "4 March 2024",
  },
  {
    Code: "B002XG6I4E",
    bookName: "The Bhagwat Gita : Symphony of the Spirit (Hindi)",
    authorName: "RR Varma",
    posterUrl: "https://m.media-amazon.com/images/I/81jj54IP54L._AC_UY218_.jpg",
    pricing: 329,
    releaseDate: "1 October 2014",
  },
  {
    Code: "B00TWE8WPA",
    bookName: "Harry Potter and the Sorcerer's Stone",
    authorName: "J.K. Rowling",
    posterUrl: "https://m.media-amazon.com/images/I/81YOuOGFCJL._AC_UY218_.jpg",
    pricing: 690,
    releaseDate: "1998-09-01",
  },
  {
    Code: "B01DYPY5OG",
    bookName: "The Lord of the Rings",
    authorName: "J.R.R. Tolkien",
    posterUrl: "https://m.media-amazon.com/images/I/81YyraOaX1L._AC_UY218_.jpg",
    pricing: 399,
    releaseDate: "23 July 2022",
  },
  {
    Code: "B009U9S6FI",
    bookName: "The Hunger Games",
    authorName: "Suzanne Collins",
    posterUrl: "https://m.media-amazon.com/images/I/61JfGcL2ljL._AC_UY218_.jpg",
    pricing: 800,
    releaseDate: "2008-09-14",
  },
  {
    Code: "B07C42H5SB",
    bookName: "The Handmaid's Tale",
    authorName: "Margaret Atwood",
    posterUrl: "https://m.media-amazon.com/images/I/61SpcaD4poL._AC_UY218_.jpg",
    pricing: 560,
    releaseDate: "1985-03-16",
  },
];
